version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: TaskManager.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=TaskManagerDb;User=sa;Password=pass@16;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "youssef@gh098"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "youssef@gh098", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
